import {
  readdirSync,
  statSync,
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedContractComment = `
/**
 * Generated by packages/foundry/scripts-js/generateTsAbis.js. Do not edit manually.
 * Identical ABIs are shared across chains; addresses remain deployment-specific.
 */`;

function getDirectories(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isDirectory();
  });
}

function getFiles(path) {
  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function parseTransactionRun(filePath) {
  try {
    const content = readFileSync(filePath, "utf8");
    const broadcastData = JSON.parse(content);
    return broadcastData.transactions || [];
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}:`, error.message);
    return [];
  }
}

function getDeploymentHistory(broadcastPath) {
  const files = getFiles(broadcastPath);
  const deploymentHistory = new Map();

  // Sort files to process them in chronological order
  const runFiles = files
    .filter(
      (file) =>
        file.startsWith("run-") &&
        file.endsWith(".json") &&
        !file.includes("run-latest")
    )
    .sort((a, b) => {
      // Extract run numbers and compare them
      const runA = parseInt(a.match(/run-(\d+)/)?.[1] || "0");
      const runB = parseInt(b.match(/run-(\d+)/)?.[1] || "0");
      return runA - runB;
    });

  for (const file of runFiles) {
    const transactions = parseTransactionRun(join(broadcastPath, file));

    for (const tx of transactions) {
      if (tx.transactionType === "CREATE") {
        // Store or update contract deployment info
        deploymentHistory.set(tx.contractAddress, {
          contractName: tx.contractName,
          address: tx.contractAddress,
          deploymentFile: file,
          transaction: tx,
        });
      }
    }
  }

  return Array.from(deploymentHistory.values());
}

function getArtifactOfContract(contractName) {
  const current_path_to_artifacts = join(
    __dirname,
    "..",
    `out/${contractName}.sol`
  );

  if (!existsSync(current_path_to_artifacts)) return null;

  const artifactJson = JSON.parse(
    readFileSync(`${current_path_to_artifacts}/${contractName}.json`)
  );

  return artifactJson;
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact?.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function processAllDeployments(broadcastPath) {
  const scriptFolders = getDirectories(broadcastPath);
  const allDeployments = new Map();

  scriptFolders.forEach((scriptFolder) => {
    const scriptPath = join(broadcastPath, scriptFolder);
    const chainFolders = getDirectories(scriptPath);

    chainFolders.forEach((chainId) => {
      const chainPath = join(scriptPath, chainId);
      const deploymentHistory = getDeploymentHistory(chainPath);

      deploymentHistory.forEach((deployment) => {
        const timestamp = parseInt(
          deployment.deploymentFile.match(/run-(\d+)/)?.[1] || "0"
        );
        const key = `${chainId}-${deployment.contractName}`;

        // Only update if this deployment is newer
        if (
          !allDeployments.has(key) ||
          timestamp > allDeployments.get(key).timestamp
        ) {
          allDeployments.set(key, {
            ...deployment,
            timestamp,
            chainId,
            deploymentScript: scriptFolder,
          });
        }
      });
    });
  });

  // One deployment set per chain: the run that deployed the pool (DecentralizedMicrocredit) last defines the
  // chain's contracts. Contracts that only older runs deployed (the MockUSDC of a retired deployment, say) are
  // dropped, so the app can never pair a new pool with a stale token entry.
  const poolRunByChain = new Map();
  allDeployments.forEach((d) => {
    if (d.contractName === "DecentralizedMicrocredit") {
      poolRunByChain.set(d.chainId, {
        script: d.deploymentScript,
        file: d.deploymentFile,
      });
    }
  });
  allDeployments.forEach((d, key) => {
    const run = poolRunByChain.get(d.chainId);
    if (
      run &&
      (d.deploymentScript !== run.script || d.deploymentFile !== run.file)
    ) {
      console.log(
        `Dropping ${d.contractName} at ${d.address} on chain ${d.chainId}: deployed by an older run than the pool (${d.deploymentFile})`
      );
      allDeployments.delete(key);
    }
  });

  const allContracts = {};

  allDeployments.forEach((deployment) => {
    const { chainId, contractName } = deployment;
    const artifact = getArtifactOfContract(contractName);

    if (artifact) {
      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address: deployment.address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
      };
    }
  });

  return allContracts;
}

export function renderContracts(contracts) {
  const abis = new Map();
  const chains = Object.entries(contracts).map(([chainId, deployed]) => {
    const entries = Object.entries(deployed).map(([name, contract]) => {
      const abi = JSON.stringify(contract.abi);
      if (!abis.has(abi)) abis.set(abi, `abi${abis.size}`);
      const fields = Object.entries(contract).map(([key, value]) => {
        const content = key === "abi" ? abis.get(abi) : JSON.stringify(value);
        return `${JSON.stringify(key)}: ${content}`;
      });
      return `${JSON.stringify(name)}: {${fields.join(",")}}`;
    });
    return `${parseInt(chainId).toFixed(0)}: {${entries.join(",")}}`;
  });
  const definitions = [...abis].map(
    ([abi, name]) => `const ${name} = ${abi} as const;`
  );
  return format(
    `${generatedContractComment}
     import type { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
     ${definitions.join("\n")}
     const deployedContracts = {${chains.join(",")}} as const;
     export default deployedContracts satisfies GenericContractsDeclaration;`,
    { parser: "typescript" }
  );
}

function main() {
  const current_path_to_broadcast = join(__dirname, "..", "broadcast");

  // Process all deployments from all script folders
  const allGeneratedContracts = processAllDeployments(
    current_path_to_broadcast
  );

  const NEXTJS_TARGET_DIR = join(__dirname, "..", "..", "nextjs", "contracts");

  // Ensure target directories exist
  if (!existsSync(NEXTJS_TARGET_DIR)) {
    mkdirSync(NEXTJS_TARGET_DIR, { recursive: true });
  }

  writeFileSync(
    join(NEXTJS_TARGET_DIR, "deployedContracts.ts"),
    renderContracts(allGeneratedContracts)
  );

  console.log(
    `📝 Updated TypeScript contract definition file on ${join(
      NEXTJS_TARGET_DIR,
      "deployedContracts.ts"
    )}`
  );
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    main();
  } catch (error) {
    console.error("Error:", error);
    process.exitCode = 1;
  }
}
